services:
  php:
    build: .
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - net
    platform: linux/arm64
  db:
    image: mysql:latest
    container_name: mysql1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"

    networks:
      - net
    platform: linux/arm64

networks:
  net:
    driver: bridge

volumes:
  db_data:

